use crate::cpg::cfg::CfgLang;

pub const PYTHON: CfgLang = CfgLang {
    if_kinds: &["if_statement"],
    loop_kinds: &["for_statement", "while_statement"],
    return_kinds: &["return_statement"],
    break_kinds: &["break_statement"],
    continue_kinds: &["continue_statement"],
    try_kinds: &["try_statement"],
    handler_kinds: &["except_clause"],
    def_kinds: &["assignment", "augmented_assignment"],
    aug_kinds: &["augmented_assignment"],
    block_kinds: &["block"],
    nested_fn_kinds: &["lambda", "function_definition"],
    switch_kinds: &["match_statement"],
    case_kinds: &["case_clause"],
    hoist_kinds: &[],
};

pub const RUST: CfgLang = CfgLang {
    if_kinds: &["if_expression"],
    loop_kinds: &["for_expression", "while_expression", "loop_expression"],
    return_kinds: &["return_expression"],
    break_kinds: &["break_expression"],
    continue_kinds: &["continue_expression"],
    try_kinds: &[],
    handler_kinds: &[],
    def_kinds: &["let_declaration", "assignment_expression", "compound_assignment_expr"],
    aug_kinds: &["compound_assignment_expr"],
    block_kinds: &["block"],
    nested_fn_kinds: &["closure_expression", "function_item"],
    switch_kinds: &["match_expression"],
    case_kinds: &["match_arm"],
    hoist_kinds: &[],
};

pub const TYPESCRIPT: CfgLang = CfgLang {
    if_kinds: &["if_statement"],
    loop_kinds: &["while_statement", "for_statement", "for_in_statement", "do_statement"],
    return_kinds: &["return_statement"],
    break_kinds: &["break_statement"],
    continue_kinds: &["continue_statement"],
    try_kinds: &["try_statement"],
    handler_kinds: &["catch_clause"],
    def_kinds: &["variable_declarator", "assignment_expression", "augmented_assignment_expression"],
    aug_kinds: &["augmented_assignment_expression"],
    block_kinds: &["statement_block"],
    nested_fn_kinds: &[
        "arrow_function",
        "function_declaration",
        "function_expression",
        "method_definition",
        "generator_function",
        "generator_function_declaration",
    ],
    switch_kinds: &["switch_statement"],
    case_kinds: &["switch_case", "switch_default"],
    hoist_kinds: &["variable_declaration"],
};

pub const JAVASCRIPT: CfgLang = TYPESCRIPT;

pub const PHP: CfgLang = CfgLang {
    if_kinds: &["if_statement"],
    loop_kinds: &["while_statement", "for_statement", "foreach_statement", "do_statement"],
    return_kinds: &["return_statement"],
    break_kinds: &["break_statement"],
    continue_kinds: &["continue_statement"],
    try_kinds: &["try_statement"],
    handler_kinds: &["catch_clause"],
    def_kinds: &["assignment_expression", "augmented_assignment_expression"],
    aug_kinds: &["augmented_assignment_expression"],
    block_kinds: &["compound_statement", "colon_block"],
    nested_fn_kinds: &["anonymous_function", "arrow_function"],
    switch_kinds: &["switch_statement"],
    case_kinds: &["case_statement", "default_statement"],
    hoist_kinds: &[],
};

pub const JAVA: CfgLang = CfgLang {
    if_kinds: &["if_statement"],
    loop_kinds: &["while_statement", "for_statement", "enhanced_for_statement", "do_statement"],
    return_kinds: &["return_statement"],
    break_kinds: &["break_statement"],
    continue_kinds: &["continue_statement"],
    try_kinds: &["try_statement"],
    handler_kinds: &["catch_clause"],
    def_kinds: &["variable_declarator", "assignment_expression"],
    aug_kinds: &[],
    block_kinds: &["block", "constructor_body"],
    nested_fn_kinds: &["lambda_expression"],
    switch_kinds: &["switch_expression"],
    case_kinds: &["switch_block_statement_group", "switch_rule"],
    hoist_kinds: &[],
};

pub const CSHARP: CfgLang = CfgLang {
    if_kinds: &["if_statement"],
    loop_kinds: &["while_statement", "for_statement", "foreach_statement", "do_statement"],
    return_kinds: &["return_statement"],
    break_kinds: &["break_statement"],
    continue_kinds: &["continue_statement"],
    try_kinds: &["try_statement"],
    handler_kinds: &["catch_clause"],
    def_kinds: &["assignment_expression", "variable_declarator"],
    aug_kinds: &[],
    block_kinds: &["block"],
    nested_fn_kinds: &["lambda_expression", "anonymous_method_expression", "local_function_statement"],
    switch_kinds: &["switch_statement"],
    case_kinds: &["switch_section"],
    hoist_kinds: &[],
};

pub const GO: CfgLang = CfgLang {
    if_kinds: &["if_statement"],
    loop_kinds: &["for_statement"],
    return_kinds: &["return_statement"],
    break_kinds: &["break_statement"],
    continue_kinds: &["continue_statement"],
    try_kinds: &[],
    handler_kinds: &[],
    def_kinds: &["short_var_declaration", "assignment_statement", "var_spec"],
    aug_kinds: &[],
    block_kinds: &["block"],
    nested_fn_kinds: &["func_literal"],
    switch_kinds: &["expression_switch_statement", "type_switch_statement"],
    case_kinds: &["expression_case", "default_case", "type_case"],
    hoist_kinds: &[],
};

pub const C: CfgLang = CfgLang {
    if_kinds: &["if_statement"],
    loop_kinds: &["while_statement", "for_statement", "do_statement"],
    return_kinds: &["return_statement"],
    break_kinds: &["break_statement"],
    continue_kinds: &["continue_statement"],
    try_kinds: &[],
    handler_kinds: &[],
    def_kinds: &["assignment_expression", "init_declarator"],
    aug_kinds: &[],
    block_kinds: &["compound_statement"],
    nested_fn_kinds: &[],
    switch_kinds: &["switch_statement"],
    case_kinds: &["case_statement"],
    hoist_kinds: &[],
};

pub const CPP: CfgLang = CfgLang {
    if_kinds: &["if_statement"],
    loop_kinds: &["while_statement", "for_statement", "for_range_loop", "do_statement"],
    return_kinds: &["return_statement"],
    break_kinds: &["break_statement"],
    continue_kinds: &["continue_statement"],
    try_kinds: &["try_statement"],
    handler_kinds: &["catch_clause"],
    def_kinds: &["assignment_expression", "init_declarator"],
    aug_kinds: &[],
    block_kinds: &["compound_statement"],
    nested_fn_kinds: &["lambda_expression"],
    switch_kinds: &["switch_statement"],
    case_kinds: &["case_statement"],
    hoist_kinds: &[],
};

pub const RUBY: CfgLang = CfgLang {
    if_kinds: &["if", "unless", "elsif", "if_modifier", "unless_modifier"],
    loop_kinds: &["while", "until", "for", "while_modifier", "until_modifier"],
    return_kinds: &["return"],
    break_kinds: &["break"],
    continue_kinds: &["next"],
    try_kinds: &[],
    handler_kinds: &[],
    def_kinds: &["assignment", "operator_assignment"],
    aug_kinds: &["operator_assignment"],
    block_kinds: &["then", "else"],
    nested_fn_kinds: &["block", "do_block", "lambda", "method", "singleton_method"],
    switch_kinds: &["case", "case_match"],
    case_kinds: &["when", "in_clause", "else"],
    hoist_kinds: &[],
};

pub const KOTLIN: CfgLang = CfgLang {
    if_kinds: &["if_expression"],
    loop_kinds: &["for_statement", "while_statement", "do_while_statement"],
    return_kinds: &["return_expression"],
    break_kinds: &[],
    continue_kinds: &[],
    try_kinds: &[],
    handler_kinds: &[],
    def_kinds: &["assignment"],
    aug_kinds: &[],
    block_kinds: &["block"],
    nested_fn_kinds: &["lambda_literal", "anonymous_function", "function_declaration"],
    switch_kinds: &["when_expression"],
    case_kinds: &["when_entry"],
    hoist_kinds: &[],
};

pub const SWIFT: CfgLang = CfgLang {
    if_kinds: &["if_statement", "guard_statement"],
    loop_kinds: &["for_statement", "while_statement", "repeat_while_statement"],
    return_kinds: &["control_transfer_statement"],
    break_kinds: &[],
    continue_kinds: &[],
    try_kinds: &[],
    handler_kinds: &[],
    def_kinds: &["property_declaration", "assignment"],
    aug_kinds: &[],
    block_kinds: &["statements"],
    nested_fn_kinds: &["lambda_literal", "function_declaration"],
    switch_kinds: &["switch_statement"],
    case_kinds: &["switch_entry"],
    hoist_kinds: &[],
};
