use std::collections::BTreeMap;
use std::process::Command;

use pulse::calibrate::emit;
use pulse::calibrate::estimator::{estimate_from_tables, EstimatorConfig};
use pulse::calibrate::priors::{LanguagePriors, MetricPrior, PriorsTable};
use pulse::calibrate::stats::GpdFit;

const PROBES: &[f64] = &[0.50, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 0.99, 0.995];

fn metric(n: u64, values: &[f64], gpd: Option<GpdFit>) -> MetricPrior {
    MetricPrior { n, weight: n as f64, quantiles: PROBES.iter().copied().zip(values.iter().copied()).collect(), gpd }
}

fn corpus() -> PriorsTable {
    let mut python = LanguagePriors::default();
    let gpd = GpdFit { threshold: 9.0, xi: 0.2, sigma: 10.0, tail_n: 100 };
    python.metrics.insert("cc".into(), metric(900, &[2.0, 3.0, 4.0, 5.0, 6.0, 9.0, 14.0, 25.0, 40.0], Some(gpd)));
    python.metrics.insert("fn_loc".into(), metric(900, &[8.0, 14.0, 18.0, 22.0, 28.0, 40.0, 60.0, 110.0, 160.0], None));
    python.metrics.insert("args".into(), metric(900, &[1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 4.0, 5.0, 6.0], None));
    let mut main = BTreeMap::new();
    main.insert("python".to_string(), python);
    PriorsTable { cpg_enabled: false, main, tests: BTreeMap::new() }
}

fn rendered_main() -> String {
    let project = corpus();
    let calibrated = estimate_from_tables(&project, &corpus(), &EstimatorConfig::default());
    emit::render(&calibrated, &EstimatorConfig::default()).main
}

#[test]
fn rendered_toml_has_language_section_and_pairs() {
    let toml = rendered_main();
    assert!(toml.contains("[languages.python]"), "{toml}");
    assert!(toml.contains("cc_warning = "), "{toml}");
    assert!(toml.contains("cc_alert = "), "{toml}");
    assert!(toml.contains("fn_loc_warning = "), "{toml}");
    assert!(toml.contains("arg_max = "), "single-valued knob present: {toml}");
    assert!(!toml.contains("args_warning"), "discrete metric must not emit a warning pair: {toml}");
}

#[test]
fn rendered_toml_carries_provenance_comments() {
    let toml = rendered_main();
    assert!(toml.contains("# cc: n="), "{toml}");
    assert!(toml.contains("lambda="), "{toml}");
    assert!(toml.contains("generated by `pulse calibrate`"), "{toml}");
}

#[test]
fn rendered_toml_round_trips_through_the_config_loader() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join(".pulse.toml"), rendered_main()).unwrap();
    let (cfg, _) = pulse::config::load_config_with_root(dir.path()).expect("config parses");
    let py = cfg.languages.get("python").expect("python thresholds");
    let warning = py.function.cc_warning.expect("cc_warning");
    let alert = py.function.cc_alert.expect("cc_alert");
    assert!(alert > warning, "alert {alert} must exceed warning {warning}");
    assert!(py.function.arg_max.is_some());
}

#[test]
fn calibrate_cli_dry_runs_then_writes() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(dir.path().join("src")).unwrap();
    std::fs::write(
        dir.path().join("src/app.py"),
        "def alpha(x):\n    if x > 1:\n        for y in range(x):\n            return y\n    return 0\n",
    )
    .unwrap();
    let bin = env!("CARGO_BIN_EXE_pulse");
    let root = dir.path().to_str().unwrap();

    let dry = Command::new(bin).args(["calibrate", "--root", root]).output().unwrap();
    let stdout = String::from_utf8_lossy(&dry.stdout);
    assert!(stdout.contains("[languages.python]"), "dry run prints config: {stdout}");
    assert!(!dir.path().join(".pulse.toml").exists(), "dry run must not write");

    let status = Command::new(bin).args(["calibrate", "--root", root, "--write"]).status().unwrap();
    assert!(status.success());
    assert!(dir.path().join(".pulse.toml").exists(), "--write saves the config");
    let (cfg, _) = pulse::config::load_config_with_root(dir.path()).expect("written config parses");
    assert!(cfg.languages.contains_key("python"));
}
