use std::collections::{BTreeMap, BTreeSet};
use std::process::Command;

use pulse::calibrate::emit;
use pulse::calibrate::estimator::{estimate_languages, Calibrated, EstimatorConfig};
use pulse::calibrate::priors::{LanguagePriors, MetricPrior};

fn mp(quantiles: &[(f64, f64)]) -> MetricPrior {
    MetricPrior { n: 900, quantiles: quantiles.to_vec(), cdf: Vec::new() }
}

fn corpus_python() -> BTreeMap<String, LanguagePriors> {
    let mut lp = LanguagePriors::default();
    lp.metrics.insert("cc".into(), mp(&[(0.5, 8.0), (0.75, 15.0), (0.95, 40.0)]));
    lp.metrics.insert("fn_loc".into(), mp(&[(0.5, 14.0), (0.75, 30.0), (0.95, 90.0)]));
    lp.metrics.insert("args".into(), mp(&[(0.5, 1.0), (0.75, 3.0), (0.95, 6.0)]));
    let mut out = BTreeMap::new();
    out.insert("python".to_string(), lp);
    out
}

fn rendered_main() -> String {
    let mut langs = BTreeSet::new();
    langs.insert("python".to_string());
    let stratum = estimate_languages(&langs, &corpus_python(), &EstimatorConfig::default());
    let calibrated = Calibrated { main: stratum, tests: BTreeMap::new() };
    emit::render(&calibrated).main
}

#[test]
fn rendered_toml_has_language_section_and_pairs() {
    let toml = rendered_main();
    assert!(toml.contains("[languages.python]"), "{toml}");
    assert!(toml.contains("cc_warning = "), "{toml}");
    assert!(toml.contains("cc_alert = "), "{toml}");
    assert!(toml.contains("arg_max = "), "single-valued knob present: {toml}");
    assert!(!toml.contains("args_warning"), "discrete metric emits no warning pair: {toml}");
}

#[test]
fn rendered_toml_explains_each_threshold_inline() {
    let toml = rendered_main();
    assert!(!toml.contains("generated by"), "no header preamble");
    assert!(toml.starts_with("[languages."), "starts straight at the first language section: {toml}");
    assert!(toml.contains("loosened to corpus") || toml.contains("editorial"), "per-field provenance: {toml}");
}

#[test]
fn rendered_toml_round_trips_through_the_config_loader() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join(".pulse.toml"), rendered_main()).unwrap();
    let (cfg, _) = pulse::config::load_config_with_root(dir.path()).expect("config parses");
    let py = cfg.languages.get("python").expect("python thresholds");
    let warning = py.function.cc_warning.expect("cc_warning");
    let alert = py.function.cc_alert.expect("cc_alert");
    assert!(alert > warning, "alert {alert} must exceed warning {warning}");
    assert!(warning >= 9, "editorial cc floor held");
}

#[test]
fn calibrate_cli_dry_runs_then_writes() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(dir.path().join("src")).unwrap();
    std::fs::write(
        dir.path().join("src/app.py"),
        "def alpha(x):\n    if x > 1:\n        for y in range(x):\n            return y\n    return 0\n",
    )
    .unwrap();
    let bin = env!("CARGO_BIN_EXE_pulse");
    let root = dir.path().to_str().unwrap();

    let dry = Command::new(bin).args(["calibrate", "--root", root]).output().unwrap();
    let stdout = String::from_utf8_lossy(&dry.stdout);
    assert!(stdout.contains("[languages.python]"), "dry run prints config: {stdout}");
    assert!(!dir.path().join(".pulse.toml").exists(), "dry run must not write");

    let status = Command::new(bin).args(["calibrate", "--root", root, "--write"]).status().unwrap();
    assert!(status.success());
    assert!(dir.path().join(".pulse.toml").exists(), "--write saves the config");
    let (cfg, _) = pulse::config::load_config_with_root(dir.path()).expect("written config parses");
    assert!(cfg.languages.contains_key("python"));
}
