use std::fmt::Write;

use super::estimator::{Calibrated, EstimatorConfig, Stratum, ThresholdPair};

enum Field {
    Pair(&'static str, &'static str),
    WarningLevel(&'static str),
    AlertLevel(&'static str),
}

const FIELD_MAP: &[(&str, Field)] = &[
    ("cc", Field::Pair("cc_warning", "cc_alert")),
    ("cogc", Field::Pair("cogc_warning", "cogc_alert")),
    ("fn_loc", Field::Pair("fn_loc_warning", "fn_loc_alert")),
    ("file_loc", Field::Pair("file_loc_warning", "file_loc_alert")),
    ("nesting", Field::WarningLevel("nesting_depth")),
    ("global_nesting", Field::WarningLevel("global_nesting_depth")),
    ("bump", Field::AlertLevel("bump_count")),
    ("args", Field::AlertLevel("arg_max")),
    ("compound_conditions", Field::AlertLevel("compound_conditions")),
    ("embedded_block_loc", Field::AlertLevel("embedded_block_loc")),
    ("consecutive_asserts", Field::AlertLevel("consecutive_asserts_max")),
    ("short_vars", Field::AlertLevel("short_var_max_count")),
    ("string_match_arms", Field::AlertLevel("max_string_match_arms")),
    ("struct_fields", Field::AlertLevel("max_struct_fields")),
    ("file_functions", Field::AlertLevel("file_function_count")),
    ("file_total_cc", Field::AlertLevel("file_total_cc")),
    ("declarations", Field::AlertLevel("max_declarations")),
    ("global_conditionals", Field::AlertLevel("global_conditionals_max")),
];

pub struct Rendered {
    pub main: String,
    pub tests: String,
}

pub fn render(calibrated: &Calibrated, cfg: &EstimatorConfig) -> Rendered {
    Rendered { main: render_stratum(&calibrated.main, cfg), tests: render_stratum(&calibrated.tests, cfg) }
}

fn render_stratum(stratum: &Stratum, cfg: &EstimatorConfig) -> String {
    let mut out = String::new();
    write_header(&mut out, cfg);
    for (lang, metrics) in stratum {
        let _ = write!(out, "\n[languages.{lang}]\n");
        for (metric, field) in FIELD_MAP {
            if let Some(pair) = metrics.get(*metric) {
                write_field(&mut out, metric, field, pair);
            }
        }
    }
    out
}

fn write_header(out: &mut String, cfg: &EstimatorConfig) {
    let _ = writeln!(out, "# generated by `pulse calibrate` — do not hand-edit, re-run to regenerate");
    let _ = writeln!(
        out,
        "# project distributions blended with corpus priors (alpha_warning={}, alpha_alert={}, prior_strength={})",
        cfg.alpha_warning, cfg.alpha_alert, cfg.prior_strength
    );
}

fn write_field(out: &mut String, metric: &str, field: &Field, pair: &ThresholdPair) {
    let _ = writeln!(out, "# {metric}: {}", provenance(pair));
    match field {
        Field::Pair(warning_field, alert_field) => {
            let warning = round(pair.warning);
            let alert = round(pair.alert).max(warning + 1);
            let _ = writeln!(out, "{warning_field} = {warning}");
            let _ = writeln!(out, "{alert_field} = {alert}");
        }
        Field::WarningLevel(name) => {
            let _ = writeln!(out, "{name} = {}", round(pair.warning));
        }
        Field::AlertLevel(name) => {
            let _ = writeln!(out, "{name} = {}", round(pair.alert));
        }
    }
}

fn provenance(pair: &ThresholdPair) -> String {
    let mut tags = format!("n={} lambda={:.2}", pair.project_n, pair.lambda);
    if pair.gpd_alert {
        tags.push_str(" tail-modeled");
    }
    if pair.clamped {
        tags.push_str(" clamped-to-corpus-band");
    }
    tags
}

fn round(value: f64) -> u32 {
    value.round().max(1.0) as u32
}
