#![allow(clippy::assigning_clones)]

pub mod analysis_cache;
pub mod analytics;
pub mod analyze;
pub mod applicability;
pub mod audit;
pub mod baseline_ratchet;
pub mod baselines;
pub use pulse_buildmeta as buildmeta;
pub mod calibrate;
pub use pulse_config as config;
pub use pulse_config::config_history;
pub use pulse_core as core;
pub use pulse_syntax::{cpg, langkinds, parse, walk};
pub mod dead_function;
pub mod extract;
pub mod framework;
pub mod history;
pub mod hook;
pub mod import_check;
pub use pulse_imports as imports;
pub mod intensity;
pub mod interaction;
pub mod naturalness;
pub mod output;
pub mod refmine;
pub mod registry;
pub mod session_clones;
pub use pulse_smells::{self as smells, duplication, module_smells};
pub mod test_detection;
pub use pulse_thresholds as thresholds;
pub mod turn_scan;
