[package]
name = "pulse-config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
pulse-core = { workspace = true }
pulse-thresholds = { workspace = true }
pulse-syntax = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
globset = { workspace = true }

[lints]
workspace = true
